/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-09-20 09:42:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<!--     <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://getbootstrap.com/docs/5.2/assets/css/docs.css\" rel=\"stylesheet\">\r\n");
      out.write("    <title>Bootstrap Example</title>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js\"></script> -->\r\n");
      out.write("  </head>\r\n");
      out.write("	<!-- 제이쿼리 -->\r\n");
      out.write("	<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("	 <link rel=\"stylesheet\" href=\"https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css\">\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js\"></script>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../main/header.jsp", out, false);
      out.write("\r\n");
      out.write("	<section>\r\n");
      out.write("	\r\n");
      out.write("		<div id=\"s_1\">\r\n");
      out.write("			<video width=\"100%\" height=\"auto\" autoplay muted loop=\"\">\r\n");
      out.write("			  <source src=\"../main/img/main_poster.mp4\" type=\"video/mp4\">\r\n");
      out.write("			  <source src=\"movie.ogg\" type=\"video/ogg\">\r\n");
      out.write("			</video>\r\n");
      out.write("			<a href=\"../sub/happle.jsp\">\r\n");
      out.write("				<p id =\"pos_txt\">제주 바다의 평화로움을 <br> 해플과 함께 느껴보세요</p>\r\n");
      out.write("			</a>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div id=\"s_2and3\">\r\n");
      out.write("			<!-- 하늘색 배경 -->\r\n");
      out.write("			<img class=\"sky\" alt=\"\" src=\"../main/img/background_sky.png\">\r\n");
      out.write("			<div id=\"s_2\">\r\n");
      out.write("				<div>\r\n");
      out.write("					<img alt=\"\" src=\"../main/img/having_idea.webp\">\r\n");
      out.write("					<p class=\"text\"> 취향 저격 여행 <br>골라보세요 > </p>\r\n");
      out.write("					\r\n");
      out.write("					<div class=\"sel\">\r\n");
      out.write("						<div class=\"select\">\r\n");
      out.write("							<p class=\"btn\">10-20대</p>\r\n");
      out.write("							<p class=\"btn\">30-40대</p>\r\n");
      out.write("							<p class=\"btn\">50대이상</p>\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("						<div class=\"select\">\r\n");
      out.write("							<p class=\"blank\"> </p>\r\n");
      out.write("							<p class=\"btn\">낮 시간</p>\r\n");
      out.write("							<p class=\"btn\">밤 시간</p>\r\n");
      out.write("						</div>\r\n");
      out.write("			\r\n");
      out.write("						<div class=\"select\">\r\n");
      out.write("							<p class=\"btn\">힐링/자연</p>\r\n");
      out.write("							<p class=\"btn\">스포츠</p>\r\n");
      out.write("							<p class=\"btn\">체험/관광</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<script>\r\n");
      out.write("	\r\n");
      out.write(" 	        $(function() {\r\n");
      out.write(" 	        	\r\n");
      out.write("	            $('.btn')\r\n");
      out.write("	            .on('mouseover', function(){\r\n");
      out.write("	                $(this).stop(true).animate({\r\n");
      out.write("	                    'backgroundColor' : '#EAF0F2',\r\n");
      out.write("	                    'color' : 'black',\r\n");
      out.write("	                    'border-radius' : '20px'\r\n");
      out.write("	                });\r\n");
      out.write("	            })\r\n");
      out.write("	            \r\n");
      out.write("	            .on('mouseout', function(){\r\n");
      out.write("	                $(this).stop(true).animate({\r\n");
      out.write("	                    'backgroundColor' : '',\r\n");
      out.write("	                    'color' : 'black'\r\n");
      out.write("	                });\r\n");
      out.write("	            })\r\n");
      out.write("	            \r\n");
      out.write("	            .on('click', function(){\r\n");
      out.write("	                $(this).css({\r\n");
      out.write("		                'backgroundColor' : '#7ACDEE',\r\n");
      out.write("		                'color' : 'white',\r\n");
      out.write("		                'border-radius' : '20px'\r\n");
      out.write("	                });\r\n");
      out.write("	            })\r\n");
      out.write("	            \r\n");
      out.write("	      		.on('mouseup', function(){\r\n");
      out.write("	                $(this).stop(true).animate({\r\n");
      out.write("	                	'backgroundColor' : '#7ACDEE',\r\n");
      out.write("		                'color' : 'white',\r\n");
      out.write("		                'border-radius' : '20px'\r\n");
      out.write("	                });\r\n");
      out.write("	            }) \r\n");
      out.write("\r\n");
      out.write("	        }); \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	        \r\n");
      out.write("\r\n");
      out.write("			</script>\r\n");
      out.write("			\r\n");
      out.write("			<div id=\"s_3\">\r\n");
      out.write("				<a><h3> 여행지 안내 > </h3></a>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"trip\">\r\n");
      out.write("					<a href=\"../sub/trip.jsp\">\r\n");
      out.write("						<img alt=\"\" src=\"../main/img/pos1.jpg\">\r\n");
      out.write("						<p>투명한 바다에서<br>땅콩아이스크림을</p><br>\r\n");
      out.write("						<p class=\"name\">제주시 우도</p>\r\n");
      out.write("					</a>\r\n");
      out.write("					<a href=\"../sub/trip.jsp\">\r\n");
      out.write("						<img alt=\"\" src=\"../main/img/pos2.jpg\">\r\n");
      out.write("						<p>피톤치드 가득,<br>여유로운 숲길산책</p>\r\n");
      out.write("						<p class=\"name\">제주시 비자림 숲길</p>\r\n");
      out.write("					</a>\r\n");
      out.write("					<a href=\"../sub/trip.jsp\">\r\n");
      out.write("						<img alt=\"\" src=\"../main/img/pos3.jpg\">\r\n");
      out.write("						<p>시원한 폭포소리를<br>들어보세요</p>\r\n");
      out.write("						<p class=\"name\">서귀포시 천지연 폭포</p>\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("<!--   <div id=\"carouselExampleIndicators\" class=\"carousel slide\" data-bs-ride=\"true\">\r\n");
      out.write("      <div class=\"carousel-indicators\">\r\n");
      out.write("        <button type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide-to=\"0\" class=\"active\" aria-current=\"true\" aria-label=\"Slide 1\"></button>\r\n");
      out.write("        <button type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide-to=\"1\" aria-label=\"Slide 2\"></button>\r\n");
      out.write("        <button type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide-to=\"2\" aria-label=\"Slide 3\"></button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"carousel-inner\">\r\n");
      out.write("        <div class=\"carousel-item active\">\r\n");
      out.write("          <svg class=\"bd-placeholder-img bd-placeholder-img-lg d-block w-100\" width=\"800\" height=\"400\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\" aria-label=\"Placeholder: First slide\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\"><title>Placeholder</title><rect width=\"100%\" height=\"100%\" fill=\"#777\"></rect><text x=\"50%\" y=\"50%\" fill=\"#555\" dy=\".3em\">First slide</text></svg>\r\n");
      out.write("    \r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"carousel-item\">\r\n");
      out.write("          <svg class=\"bd-placeholder-img bd-placeholder-img-lg d-block w-100\" width=\"800\" height=\"400\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\" aria-label=\"Placeholder: Second slide\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\"><title>Placeholder</title><rect width=\"100%\" height=\"100%\" fill=\"#666\"></rect><text x=\"50%\" y=\"50%\" fill=\"#444\" dy=\".3em\">Second slide</text></svg>\r\n");
      out.write("    \r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"carousel-item\">\r\n");
      out.write("          <svg class=\"bd-placeholder-img bd-placeholder-img-lg d-block w-100\" width=\"800\" height=\"400\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\" aria-label=\"Placeholder: Third slide\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\"><title>Placeholder</title><rect width=\"100%\" height=\"100%\" fill=\"#555\"></rect><text x=\"50%\" y=\"50%\" fill=\"#333\" dy=\".3em\">Third slide</text></svg>\r\n");
      out.write("    \r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide=\"prev\">\r\n");
      out.write("        <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("        <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("      </button>\r\n");
      out.write("      <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide=\"next\">\r\n");
      out.write("        <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("        <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("      </button>\r\n");
      out.write("    </div> -->\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	</section>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../main/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
