/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-09-20 09:42:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.sub;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class tour_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("	<link href=\"../resource/css/tour.css\" rel=\"stylesheet\">\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"night\">\r\n");
      out.write("		<video width=\"100%\" height=\"auto\" defaultPlaybackRate=\"0.1\" autoplay muted loop=\"\">\r\n");
      out.write("		  <source src=\"../sub/img/night_sky2.mp4\" type=\"video/mp4\">\r\n");
      out.write("		  <source src=\"movie.ogg\" type=\"video/ogg\">\r\n");
      out.write("		</video>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("<div id=\"tour\">\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<div id=\"h_wrap\">\r\n");
      out.write("		<header>\r\n");
      out.write("			<div id=\"hp_logo\">\r\n");
      out.write("				<a href=\"../main/main.jsp\"><img src=\"../sub/img/happleWhite.png\" alt=\"로고\"></a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</header>\r\n");
      out.write("		\r\n");
      out.write("		<nav>\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li>\r\n");
      out.write("					<a id=\"a\" href=\"../sub/happle.jsp\" style=\"color:white;\">HAPPLE소개</a><br>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li>\r\n");
      out.write("					<a href=\"../sub/trip.jsp\" style=\"color:white;\">여행지안내</a>\r\n");
      out.write("				</li>	\r\n");
      out.write("				<li>\r\n");
      out.write("					<a href=\"../sub/tour.jsp\" style=\"color:white;\">야경투어</a>\r\n");
      out.write(" 				</li>	\r\n");
      out.write("				<li>\r\n");
      out.write("					<a href=\"../sub/promotion.jsp\" style=\"color:white;\">프로모션</a>\r\n");
      out.write(" 				</li>			\r\n");
      out.write("			</ul>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"navLine\"></div>\r\n");
      out.write("			\r\n");
      out.write("			<div id=\"member\">\r\n");
      out.write("				<a href=\"../login/login.jsp\" style=\"color:white;\"><p>로그인</p></a>\r\n");
      out.write("				<a href=\"../login/join.jsp\" style=\"color:white;\"><p>회원가입</p></a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</nav>	\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		<div id=\"lb-audio\">\r\n");
      out.write("			  <audio controls>\r\n");
      out.write("			    <source src=\"//bit.ly/3euuS7B\" type=\"audio/mpeg\">  \r\n");
      out.write("			  </audio>\r\n");
      out.write("  		</div>\r\n");
      out.write("  		\r\n");
      out.write("  		<div id=\"book\">\r\n");
      out.write("			<a><p>투어 예약안내</p></a>\r\n");
      out.write("		</div>\r\n");
      out.write("  	</div> \r\n");
      out.write("\r\n");
      out.write("</div>		\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../main/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
